services:
  auth-service:
    container_name: auth-service
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
