openapi: 3.0.3
info:
  title: Auth Service API
  version: 1.0.0
  description: >-
    OpenAPI för autentiserings- och användarhanteringstjänster i simning.ax-miljön

servers:
  - url: http://localhost:8080

paths:
  /users:
    post:
      summary: Create user
      operationId: createUser
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid JSON
        '409':
          description: User already exists
        '422':
          description: Validation error

components:
  schemas:
    CreateUserRequest:
      type: object
      required:
        - email
        - firstName
        - lastName
        - magicLinks
        - otps
        - totps
      properties:
        email:
          type: string
          format: email
          example: test@example.com
        firstName:
          type: string
          minLength: 2
          example: User
        lastName:
          type: string
          minLength: 2
          example: Name
        logins:
          $ref: '#/components/schemas/UserLoginMethods'
    
    User:
      type: object
      required:
        - id
        - email
        - firstName
        - lastName
        - roles
        - createdAt
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        firstName:
          type: string
        lastName:
          type: string
        roles:
          type: array
          items:
            type: string
          example:
            - user
        logins:
          $ref: '#/components/schemas/UserLoginMethods'
        createdAt:
          type: string
          format: date-time


    UserLoginMethods:
      type: object
      required:
        - magicLinks
        - otps
        - totps
      properties:
        magicLinks:
          type: boolean
          description: Indicates whether the user can sign in using magic links.
          example: true

        otps:
          type: boolean
          description: Indicates whether the user can sign in using one-time passwords.
          example: true

        totps:
          type: boolean
          description: Indicates whether the user can sign in using time-based one-time passwords.
          example: false
